// flow-typed signature: 189f17b26e6fc3a82d4666a3f802fb10
// flow-typed version: <<STUB>>/react-flip-move_v^2.6.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-flip-move'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-flip-move' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-flip-move/dist/react-flip-move' {
  declare module.exports: any;
}

declare module 'react-flip-move/dist/react-flip-move.min' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/dom-manipulation' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/enter-leave-presets' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/error-messages' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/FlipMove' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/index' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/polyfills' {
  declare module.exports: any;
}

declare module 'react-flip-move/lib/prop-converter' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/dom-manipulation' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/enter-leave-presets' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/error-messages' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/FlipMove' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/helpers' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/index' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/polyfills' {
  declare module.exports: any;
}

declare module 'react-flip-move/src/prop-converter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-flip-move/dist/react-flip-move.js' {
  declare module.exports: $Exports<'react-flip-move/dist/react-flip-move'>;
}
declare module 'react-flip-move/dist/react-flip-move.min.js' {
  declare module.exports: $Exports<'react-flip-move/dist/react-flip-move.min'>;
}
declare module 'react-flip-move/lib/dom-manipulation.js' {
  declare module.exports: $Exports<'react-flip-move/lib/dom-manipulation'>;
}
declare module 'react-flip-move/lib/enter-leave-presets.js' {
  declare module.exports: $Exports<'react-flip-move/lib/enter-leave-presets'>;
}
declare module 'react-flip-move/lib/error-messages.js' {
  declare module.exports: $Exports<'react-flip-move/lib/error-messages'>;
}
declare module 'react-flip-move/lib/FlipMove.js' {
  declare module.exports: $Exports<'react-flip-move/lib/FlipMove'>;
}
declare module 'react-flip-move/lib/helpers.js' {
  declare module.exports: $Exports<'react-flip-move/lib/helpers'>;
}
declare module 'react-flip-move/lib/index.js' {
  declare module.exports: $Exports<'react-flip-move/lib/index'>;
}
declare module 'react-flip-move/lib/polyfills.js' {
  declare module.exports: $Exports<'react-flip-move/lib/polyfills'>;
}
declare module 'react-flip-move/lib/prop-converter.js' {
  declare module.exports: $Exports<'react-flip-move/lib/prop-converter'>;
}
declare module 'react-flip-move/src/dom-manipulation.js' {
  declare module.exports: $Exports<'react-flip-move/src/dom-manipulation'>;
}
declare module 'react-flip-move/src/enter-leave-presets.js' {
  declare module.exports: $Exports<'react-flip-move/src/enter-leave-presets'>;
}
declare module 'react-flip-move/src/error-messages.js' {
  declare module.exports: $Exports<'react-flip-move/src/error-messages'>;
}
declare module 'react-flip-move/src/FlipMove.js' {
  declare module.exports: $Exports<'react-flip-move/src/FlipMove'>;
}
declare module 'react-flip-move/src/helpers.js' {
  declare module.exports: $Exports<'react-flip-move/src/helpers'>;
}
declare module 'react-flip-move/src/index.js' {
  declare module.exports: $Exports<'react-flip-move/src/index'>;
}
declare module 'react-flip-move/src/polyfills.js' {
  declare module.exports: $Exports<'react-flip-move/src/polyfills'>;
}
declare module 'react-flip-move/src/prop-converter.js' {
  declare module.exports: $Exports<'react-flip-move/src/prop-converter'>;
}
