// flow-typed signature: 35df173dde267d1b2d98c96e03db3317
// flow-typed version: <<STUB>>/reconnecting-websocket_v^3.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reconnecting-websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reconnecting-websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reconnecting-websocket/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reconnecting-websocket/dist/index.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/index'>;
}
