// flow-typed signature: 8d4e3447309418a47f68901573e782b0
// flow-typed version: <<STUB>>/sw-precache_v^5.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sw-precache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sw-precache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sw-precache/cli' {
  declare module.exports: any;
}

declare module 'sw-precache/lib/functions' {
  declare module.exports: any;
}

declare module 'sw-precache/lib/sw-precache' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sw-precache/cli.js' {
  declare module.exports: $Exports<'sw-precache/cli'>;
}
declare module 'sw-precache/lib/functions.js' {
  declare module.exports: $Exports<'sw-precache/lib/functions'>;
}
declare module 'sw-precache/lib/sw-precache.js' {
  declare module.exports: $Exports<'sw-precache/lib/sw-precache'>;
}
